application:
  port: 8000
  hmac_secret: "long-and-very-secret-key"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "hello@jaydanhoward.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
