application:
  port: 8000
  hmac_secret: "47dfd3c4070c965b9884ebf7c53bdc0b810a496d6baea52f538f2d9a36566891"
  redis_uri: "redis://127.0.0.1:6379"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "hello@jaydanhoward.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
